const MAX_MEMO_LENGTH = 300;

const MAX_CANDIDATE_LENGTH = 4;

const MAX_TAG_LENGTH = 5;

const MAX_TITLE_LENGTH = 30;

export {
  MAX_MEMO_LENGTH,
  MAX_CANDIDATE_LENGTH,
  MAX_TAG_LENGTH,
  MAX_TITLE_LENGTH,
};
