const DAY_TO_MINUTE = 24 * 60;
const TIMETABLE_CELL_UNIT = 15;
const TIMETABLE_CELL_AMOUNT = Math.ceil(DAY_TO_MINUTE / TIMETABLE_CELL_UNIT);
const TIMETABLE_CELL_PER_HOUR = Math.floor(60 / TIMETABLE_CELL_UNIT);

export {
  DAY_TO_MINUTE,
  TIMETABLE_CELL_UNIT,
  TIMETABLE_CELL_AMOUNT,
  TIMETABLE_CELL_PER_HOUR,
};
